In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
a1 = np.array([1, 2, 3])

# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])


In [4]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a2.shape

(2, 3)

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [10]:
a2_reshape = a2.reshape(2,3,1)

In [11]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [15]:
#transpose
a2.T 

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [16]:
a2.T.shape

(3, 2)

In [17]:
a2.shape

(2, 3)

In [18]:
a3.shape

(2, 3, 3)

In [19]:
a3.T.shape

(3, 3, 2)

## dot product

In [20]:
np.random.seed(0)
mat1 = np.random.randint(10, size = (5,3))
mat2 = np.random.randint(10, size = (5,3))

In [21]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [22]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [23]:
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]], dtype=int32)

In [28]:
mat3 = np.dot(mat1,mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

In [29]:
mat3.shape

(5, 5)

## nut butter example

In [31]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [32]:
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales


Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [33]:
prices = np.array([10, 8, 12])
prices


array([10,  8, 12])

In [34]:
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=["Price"],
                             columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices.shape


(1, 3)

In [35]:
weekly_sales.shape


(5, 3)

In [36]:
total_sales = prices.dot(sales_amounts.T)
total_sales


array([240, 138, 458, 232, 142])

In [37]:
butter_prices.shape, weekly_sales.shape


((1, 3), (5, 3))

In [38]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales


Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [39]:
weekly_sales["Total"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total
Mon               12             15              0    240
Tues               3              3              7    138
Wed                9             19             18    458
Thurs              4              6             12    232
Fri                1              6              7    142

## comparison operators

In [40]:
a1

array([1, 2, 3])

In [41]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [42]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [43]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [44]:
a1 > 5

array([False, False, False])

In [45]:
a1 == a1

array([ True,  True,  True])

In [46]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

## sorting arrays

In [48]:
random_array = np.array([[8, 7, 6],
       [4, 2, 7],
       [6, 0, 6],
       [0, 8, 5],
       [6, 2, 9]])


In [49]:
random_array

array([[8, 7, 6],
       [4, 2, 7],
       [6, 0, 6],
       [0, 8, 5],
       [6, 2, 9]])

In [50]:
np.sort(random_array)


array([[6, 7, 8],
       [2, 4, 7],
       [0, 6, 6],
       [0, 5, 8],
       [2, 6, 9]])

In [53]:
# returns the original index
np.argsort(random_array)


array([[2, 1, 0],
       [1, 0, 2],
       [1, 0, 2],
       [0, 2, 1],
       [1, 0, 2]])

In [54]:
a1

array([1, 2, 3])

In [55]:
np.argsort(a1)


array([0, 1, 2])

In [56]:
np.argmin(a1)


np.int64(0)

In [57]:
np.argmax(random_array, axis=1)


array([0, 2, 0, 1, 2])

In [58]:
random_array

array([[8, 7, 6],
       [4, 2, 7],
       [6, 0, 6],
       [0, 8, 5],
       [6, 2, 9]])

In [59]:
np.argmin(random_array, axis=0)


array([3, 2, 3])

<img src="images/panda.png" />

# images into an array

In [69]:
from matplotlib.image import imread

panda = imread('./images/panda.png')
print(type(panda))


<class 'numpy.ndarray'>


In [70]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [71]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

<img src= "images/car-photo.png" />

In [74]:
car = imread("images/car-photo.png")
car.shape

(431, 575, 4)

<img src="images/dog-photo.png" />

In [75]:
dog = imread("images/dog-photo.png")
dog.shape

(432, 575, 4)

In [76]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274